DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^empty/$', app.views.empty, name='empty'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^blog', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls', namespace='app')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product_list$', app.views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        app.views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        app.views.product_detail,
        name='product_detail'),   


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = ([
    # Examples:
    url(r'^my_orders$', views.my_orders, name='my_orders'),
    
    ])

cart/urls.py
from django.conf.urls import url
from . import views

app_name='cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app import forms
from django.views.decorators.http import require_POST
from app.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "app/layout.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
<div class="anketa_1">
    <h1 style="text-align:center;font-family:fantasy">Товары в корзине</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Убрать</th>
            <th>Цена товара</th>
            <th>ИТОГО</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img style="width:120px; height:130px"
                                 src="
                              
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">✓</a></td>
                    <td class="num">{{ item.price }} ₽</td>
                    <td class="num">{{ item.total_price }} ₽</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>ИТОГО</td>
            <td colspan="4"></td>
            <td class="num" style="color:brown; font-size:18px">{{ cart.get_total_price }} ₽</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
	 <a href="{% url "product_list" %}" class="button blue">
         <i>Продолжить покупки</i>
	 </a>
	 <a href="{% url "orders:order_create" %}" class="button purple">
         <i>Купить</i>
	 </a>
    </p>
</div>
{% endblock %}

cart/templates/cart/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>