DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^empty/$', app.views.empty, name='empty'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^anketa$', app.views.anketa, name='anketa'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^blog', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls', namespace='app')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product_list$', app.views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        app.views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        app.views.product_detail,
        name='product_detail'),   


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    ]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = ([
    # Examples:
    url(r'^my_orders$', views.my_orders, name='my_orders'),
    
    ])

cart/urls.py
from django.conf.urls import url
from . import views

app_name='cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog
from django.contrib import admin
from .models import Category, Product



class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
class AnketaForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
    ok = forms.ChoiceField(label='Понравился ли Вам наш сайт', choices=[('1','Да'),('2','Нет')],
                               widget=forms.RadioSelect, initial=1)
    gender = forms.ChoiceField(label='Сколько у вас животных', choices=[('1','1'),('2','2'),('3','3'),('4','Больше 3-х')],
                               widget=forms.RadioSelect, initial=1)
    internet= forms.ChoiceField(label='Какие у вас домашние животные',
                                 choices=(('1','Собака'),
                                          ('2','Кошка'),
                                          ('3','Попугай'),
                                          ('4','Хомяк'),
                                          ('5','Несколько животных разных видов')), initial=1)
    notice = forms.BooleanField(label='Получать новости с сайта на email', required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length=7)
    message = forms.CharField(label='Ваши пожелания и вопросы', 
                              widget=forms.Textarea(attrs={'rows':12, 'cols':20}))
class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description', 'content', 'image',)
        labels = {'title': "Заголовок", 'description': "Краткое содержание", 'content': "Полное содержание", 'image': "Картинка",}

class CategoryAdmin(admin.ModelAdmin):
    list_display = ['name', 'slug']
    prepopulated_fields = {'slug': ('name',)}
admin.site.register(Category, CategoryAdmin)


class ProductAdmin(admin.ModelAdmin):
    list_display = ['name', 'slug', 'price', 'stock', 'available', 'created', 'updated']
    list_filter = ['available', 'created', 'updated']
    list_editable = ['price', 'stock', 'available']
    prepopulated_fields = {'slug': ('name',)}
admin.site.register(Product, ProductAdmin)

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}


<div style="text-align:center">
    <p1 style="font-size:25px; color:darkgreen; width:15px"> Вас приветствует интернет магазин зоотоваров "Любимые Лапки".</p1><br><br />
</div> 
    <img align="left" hspace="18" vspace="10" src="{% static 'app/content/150.jpg' %}" alt="Животные" width="500" height="400"  /><br />
<div style="font-size:16px; font-family:'Times New Roman', Times, serif; color:indigo">    
    <p4>Онлайн-зоомагазин, как и обычный магазин должен обладать удобством поиска нужного Вам товара.
    Наш большой зоомагазин, несмотря на широкий ассортимент, приятно удивит Вас простотой пользования сайтом и поиска товара. 
    Подробное описание и наличие фотографий позволят Вам составить полное представление о товаре.
    Все товары удобно сгруппированы и могут быть отобраны по различным свойствам благодаря действующей системе фильтров. 
    </p4>
</div><br />
<div style="font-size:16px; color:maroon; font-family:'Times New Roman', Times, serif">
    <ul2> В нашем магазине вы можете приобрести:
        <li><span>&#10008;</span>Корма для разных видов животных:от самых маленьких до самых больших</li>
        <li><span>&#10008;</span>Аксессуары для собак и кошек</li> <img src="static/app/content/gif.gif" class="rightimg" />
        <li><span>&#10008;</span>Различные виды домиков и клеток для Ваших милых питомцев</li>
        <li><span>&#10008;</span>Витаминки для поддержания иммунитета Вашего "друга"</li>
        <li><span>&#10008;</span>И многое другое!</li>
    </ul2>

</div>

{% endblock %}

app/templates/app/anketa.html
{% extends "app/layout.html" %}

{% block content %}


{% if form != None %}
   <br><h2 style=" font-family:fantasy; text-align:center">Пожалуйста пройдите опрос</h2><br>
    <div>
        <form method="POST">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }} <br>
        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
        {{ form.city }} <br>
        <label for="{{ form.ok.id_for_label }}">{{ form.ok.label }}:</label>
        {{ form.ok }} <br>
        <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
        {{ form.gender }}
        <label for="{{ form.internet.id_for_label }}">{{ form.internet.label }}:</label>
        {{ form.internet }} <br>
        <label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}:</label>
        {{ form.notice }} <br>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }} <br>
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label>
        {{ form.message }} <br>
        <input type="submit" value="Отправить" id="in">
        </form>
    </div>
{% else %}
    <br><h2 style="font-family:fantasy">!!! Благодарим за ваш ответ !!!</h2>
    <h3>Вы сообщили нам следующую информацию:</h3>
    <ul>
        <li><span>Имя:</span> {{ data.name }}</li>
        <li><span>Город:</span> {{ data.city }}</li>
        <li><span>Понравился ли вам наш сайт:</span> {{ data.ok }}</li>
        <li><span>Количество животных:</span> {{ data.gender }}</li>
        <li><span>Животные:</span> {{ data.internet }}</li>
        <li><span>Получать новости с сайта:</span> 
               {{ data.notice }}
         </li>
        <li><span>Ваш email:</span> {{ data.email }}</li>
        <li><span>Ваши пожелания и вопросы:</span> {{ data.message }}</li>
    </ul>
{% endif %}
<script>

function in_mouseover()
   {
        $('#in').css('background-color', 'MediumSlateBlue')
   }
    $('#in').mouseover(in_mouseover);
function in_mouseout()
   {
        $('#in').css('background-color', 'white')
   }
    $('#in').mouseout(in_mouseout);

function name_focus()
   {
        $('#id_name').css('background-color', 'LightSkyBlue')
   }
    $('#id_name').focus(name_focus);
function name_blur()
   {
        $('#id_name').css('background-color', 'white')
   }
    $('#id_name').blur(name_blur);

function city_focus()
   {
        $('#id_city').css('background-color', 'LightSkyBlue')
   }
    $('#id_city').focus(city_focus);
function city_blur()
   {
        $('#id_city').css('background-color', 'white')
   }
    $('#id_city').blur(city_blur);

function email_focus()
   {
        $('#id_email').css('background-color', 'LightSkyBlue')
   }
    $('#id_email').focus(email_focus);
function email_blur()
   {
        $('#id_email').css('background-color', 'white')
   }
    $('#id_email').blur(email_blur);

function message_focus()
   {
        $('#id_message').css('background-color', 'LightSkyBlue')
   }
    $('#id_message').focus(message_focus);
function message_blur()
   {
        $('#id_message').css('background-color', 'white')
   }
    $('#id_message').blur(message_blur);

</script>
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<h2 style=" font-family:fantasy; text-align:center">{{ title }}</h2> 
{% for post in posts %}


<hr class="hr-vertical-gradient">

<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее ⮚</a> </p>
</div>

{% endfor %}
 <style>
.hr-vertical-gradient {
	margin: 20px 0;
	padding: 0;
	height: 7px;
	border: none;
	background: linear-gradient(180deg, NavajoWhite, indigo);
}
</style>

{% endblock %}


 

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<p><a href="{% url 'blog' %}">⮘Назад </a></p>

<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
    <img class ="left" src="{{post_1.image.url}}" alt="Картинка" width="400" height="400" />
{% endif %}

{% autoescape off%}
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}
<br />
{% endautoescape %}

{% if user.is_authenticated %}
    <h3 style="font-size:x-large">Добавить комментарий</h3>
    <form method="POST">{% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>
{% else %}
<br />
    <h3 style="font-size:medium; color:maroon"><b><ins> Для добавления своего комментария, пожалуйста, <a href="{% url 'login' %}">войдите в аккаунт</a> или <a href="{% url 'registration'%}">зарегистрируйтесь.</a></ins></b></h3>
{% endif %}

{% for comment in comments %}
    <hr1/>
<div style="padding-left:10px; background: linear-gradient(90deg, rgba(244,244,252,1) 0%, rgba(250,241,187,0.7791491596638656) 35%, rgba(178,229,255,1) 100%); border: 1px solid black;">
    <h7 style="font-variant:small-caps"> {{comment.date}} </h7>
    <h5 style="color:maroon; font-size:18px"><ins> {{comment.author}}</ins></h5>
    <p style="color:darkblue; font:italic 18px bold "Times New Roman", Times, serif"> {{comment.text|linebreaksbr}} </p>
</div>
{% endfor %}

{% endblock %}

app/templates/app/detail.html
{% extends "app/layout.html" %}
{% load static %}

{% block content %}

<div class="anketa_1">
    <div class="item_3">
        <img width="250" height="300" align="left" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "media/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p style="font-family:serif;font-size:medium; color:maroon;" class="price"><b>Цена: {{ product.price }} ₽</p></b>
        <p2>{{ product.description|linebreaks }}</p2>
        <hr>
    </div>
{% if not user.is_superuser and not user.is_staff %}
  {% if user.is_authenticated %}
    
    <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {{ item.quantity }}
    {% csrf_token %}
    <input type="submit" value="Поместить в корзину">
    </form>
   
   {% else %}
    <h3 style="font-size:medium; color:maroon"><b><ins> Для добавления товара в корзину, пожалуйста, <a href="{% url 'login' %}">войдите в аккаунт</a> или <a href="{% url 'registration'%}">зарегистрируйтесь.</a></ins></b></h3>
  {% endif %}
    {% else %}
     <h3 style="font-size:medium; color:maroon"><b><ins> Вы являетесь администратором или менеджером.</ins></b></h3>
{% endif %}
</div>


{% endblock %}

app/templates/app/empty.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
 <h3 style="font-family:fantasy; font-size:22px">Список заказов пуст</h3>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
 <p style="color:black; text-align: center; font-size:35px; font-family:fantasy; color:maroon" >!!! Скидки !!!!<br />
     <ul style="color:black; font-size:20px; font-family:'Ink Free'" > Действуют скидки, в зависимости от дня недели:<br />
      <li<span>&#10004;</span>ПН, ВТ - 20% на все корма;</li><br /> <img src="static/app/content/gif3.gif" class="rightimg" />
      <li<span>&#10004;</span>СР, ЧТ - 10% на все аксессуары;</li> <br />
      <li<span>&#10004;</span>ПТ, СБ, ВС - 10% на все товары.</li><br /> 
    </ul>
    <ul1 style="color:black;font-size:20px; font-family:'Ink Free'  "> А также сейчас действуют персональные скидки по некоторым категориям товаров:
      <li><span>&#10071;</span>2 по цене 1: действует на кошачьи корма и лакомства (при покупке от 10 штук);</li>
      <li><span>&#10071;</span>1+1=3: действует на все лакомства для собак;</li>
      <li><span>&#10071;</span>скидка 20% при покупке от 15 штук: действует на все игрушки для животных.</li>
    </ul1>
   *Скидки не суммируются! Т.е. не зависят от дня недели.
</p>


<div id="myCarousel"  class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div   class="carousel-inner" role="listbox">
      <div class="item active">
        <a class="btn btn-default" href="http://porcelan-food.ru/produkty/sukhie-korma/porcelan-dlja-sobak/" target="_blank">
            <img src="{% static 'app/content/4565.jpg'%} " alt="Первый слайд" class="img-responsive" />
        
          <div class="carousel-caption" role="option">
                <p>
                </p>
          </div>
        </a>
      </div>
        <div class="item">
         <a class="btn btn-default" href="https://www.propartner.ru/tags/korm-vernye-druzya?yclid=6628029471021914782&utm_campaign=%7Bdirect%7D" target="_blank">
            <img src="{% static 'app/content/banner2.jpg'%}" alt="Второй слайд"  class="img-responsive" />
          <div class="carousel-caption" role="option">
                <p>
                </p>
          </div>
          </a>
        </div>
        <div class="item">
         <a class="btn btn-default" href="https://diusapet.com/alleva/" target="_blank">
            <img src=" {% static 'app/content/20.jpeg'%} " alt="Третий слайд"  class="img-responsive" />
          <div class="carousel-caption" role="option">
                <p>
                </p>
          </div>
         </a>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Назад</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Дальше</span>
    </a>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - FavoritePaws</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'app/content/favicon.ico' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img style="width:40px" src="{% static 'app/content/orig1.png' %}" alt="купи" /> </a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-collapse">
                <ul class="nav navbar-nav" style="font-size:15px">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'product_list' %}">Каталог</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Партнеры</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'anketa' %}">Опрос</a></li>
                    <li><a  href="{% url 'blog' %}">Блог</a></li>
                    {% endif %}
                    {% if user.is_staff and not user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Новая статья</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a  href="{% url 'videopost' %}">Видео</a></li>
                    {% endif %}
                    {% if not user.is_staff and user.is_authenticated and not user.is_superuser %}
                    <li><a  href="{% url 'app:my_orders' %}">Мои заказы</a></li>
                    <li>
                                <div style=" color:gold; font-variant:small-caps"class="navbar-collapse collapse" id="korzina">  <!--Вывод корзины-->
                                    {% with total_items=cart|length %}
                                    {% if cart|length > 0 %}
                                    Корзина:
                                    <a style="color:lime" href="{% url "cart:cart_detail" %}">
                                    {{ total_items }}шт., 
                                    {{ cart.get_total_price }} ₽
                                    </a>
                                    {% else %}
                                    Корзина пуста
                                    {% endif %}
                                    {% endwith %}
                      
                                </div>
                    </li>
                   
                    
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} </p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<h2 style=" font-family:fantasy; text-align:center">{{ title }}.</h2>
<h3 style=" font-family:'Times New Roman', Times, serif">{{ message }}</h3>
<a href ="https://ilike.pet/ru/pets/" target="_blank"> <img src="{% static 'app/content/2.jpg' %}" alt="Logo 1"/></a>
<p style="font-size:20px; color:maroon; font-family:fantasy">Сайт на котором можно посмотреть различные виды домашних животных.</p>
<a href ="https://www.petshop.ru/" target="_blank"> <img src="{% static 'app/content/1.jpg' %}" alt="Logo 1"/></a>
<p style=" font-size:20px; color:darkorange; font-family:fantasy">Сайт с обзором товаров для животных.</p>
<a href ="https://zoopskov.ru/" target="_blank"> <img src="{% static 'app/content/3.jpg' %}" alt="Logo 1"/></a>
<p style=" font-size:20px; color:darkgreen; font-family:fantasy">Сайт на котором можно посмотреть различные питомники для собак и кошек.</p>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2 style="font-family:fantasy">{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Введите логин и пароль</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Логин или пароль введены неверно!!!</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/my_orders.html
{% extends "app/layout.html" %}

{% block content %}



<h2 style="font-family:fantasy; text-align: center">Ваши заказы</h2>

{% for item in product_ordered %}
 <p style="font-size: 20px"><b><ins>Номер заказа: {{item.order_id}} </ins></b></p> 
  {% with product=item.product %}
    
  <p style="font-size: 17px ; color:darkblue"><b>Наименование продуктов: {{product.name}}</b></p>
  <p style="font-family:serif;font-size:17px; color:maroon"> <b>Цена: {{item.price}}</b></p>
  <p style="font-size: 17px ; color:indigo"><b>Количество: {{item.quantity}}</b></p>
  
<hr class="hr020">
 {% endwith %}      
 <br/>

{% endfor%}


<style>
.hr020 {
border: 0;
height: 1px;
background: #000;
background-image: -webkit-linear-gradient(left, #fff, #000, #fff);
background-image: -moz-linear-gradient(left, #fff, #000, #fff);
background-image: -ms-linear-gradient(left, #fff, #000, #fff);
background-image: -o-linear-gradient(left, #fff, #000, #fff);
}
</style>


{% endblock %}

app/templates/app/product_list.html
{% extends "app/layout.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div class="container content">
    <div class="row">
        <div class="col-md-4">
            <div class="list-group">
                <p class="list-group-item"; style="font-size:30px; font-family:fantasy"><b>Категории</b></p>
                {% if not category %}{% endif %}
                <a href="{% url "product_list" %}"; class="list-group-item">Все</a>          
                {% for c in categories %}
                <a {% if category.slug == c.slug %}{% endif %}></a>
                <a href="{{ c.get_absolute_url }}"; class="list-group-item" >{{ c.name }}</a>         
                {% endfor %}
            </div>
        </div>
		<div class="col-md-8 products">
            <div class="row">
                {% for product in products %}
                <div class="col-sm-4">
                   
                        <div class="product">                        
                          <div class="product-img">
                             <img  src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %} {% endif %}" width="170" height="170">                                
                          </div>                            
                          <a href="{{ product.get_absolute_url}}"></a>
                          <p class="product-title">
                             <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                          </p>
                          <p class="product-price"; style="font-variant:small-caps; font-size:20px"><b>Цена: {{ product.price }} ₽</p></b>       
                        </div>
                                         
                </div>
                {% endfor %} 
            </div>
        </div>
    </div>
  </div>

{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

    <h2 style=" font-family:fantasy">Регистрация пользователя</h2>

    <form method="POST" > {% csrf_token %}

    <div>

        {{ regform.as_p }}

        <button type="submit" class="save btn btn-default" > Зарегистрировать </button>

    </div>

</form>

{% endblock %}

app/templates/app/videopost.html
{%extends "app/layout.html"%}

{% block content%}

<div>
    <h1 style="font-family:fantasy; font-size:22px; color:midnightblue">Собака породы Самоед</h1>
    <VIDEO src="/media/11.mp4" controls="controls" width="400" height="300" poster="/media/11.jpg" ></VIDEO>
</div>
<hr/>
<div>
    <h1 style="font-family:fantasy; font-size:22px; color:maroon">Милые хомячки</h1>
    <VIDEO src="/media/12.mp4" controls="controls" width="400" height="300" poster="/media/12.jpg" ></VIDEO>
</div>
   

{% endblock %}